### ISSUE TITLE
Adding component in slot shows up as error

### ISSUE THREAD

**Issue by krissvaa** [vaadin/react-components#113] opened 2023-06-06 12:03 UTC
### Problem  
Using  component slots works fine, but usage shows up as a typescript error in code editors

For now there is workaround with using `{/* @ts-ignore*/}`

Example code:
```
<TextField name="Topic search"
                       title="Topic search"
                       placeholder="Search topics..."
                       value={topicSearch}
                       className="w-full mr-s">
                {/* @ts-ignore*/}
                <Icon slot='suffix'/>
            </TextField>
```

### Suggestion 
Create a new wrapper component to specify the slot that should be used for child components.

Suggestion example:
```
<TextField name="Topic search"
                       title="Topic search"
                       placeholder="Search topics..."
                       value={topicSearch}
                       className="w-full mr-s">
              <Slot slot='suffix' >
                    <Icon/>
              </Slot>
            </TextField>
```

**Comment by web-padawan** [comment] 2023-12-06 11:25
Couldn't reproduce this with the latest React wrappers. Corresponding [docs example](https://github.com/vaadin/docs/blob/d19b424d972b4e29e8366bb467b53f56a671dfd8/frontend/demo/component/textfield/react/text-field-basic.tsx#L10C3-L12) compiles without errors. Closing.

**Closed by web-padawan** 2023-12-06 11:25 UTC
