### ISSUE TITLE
When using indeterminate, one checkbox turn them off all

### ISSUE THREAD

**Issue by cromoteca** [vaadin/react-components#65] opened 2023-03-15 10:20 UTC
In the React component documentation I'm trying to replicate the indeterminate checkbox example from [docs](https://github.com/vaadin/docs/blob/a13cb1289189eb236cfa84c2ad5d9203a1c981e0/frontend/demo/component/checkbox/checkbox-indeterminate.ts) with [this](https://github.com/cromoteca/component-docs/blob/306b4372d4fa8c5d1eaba826f59abae9cc5b818e/frontend/views/checkbox/CheckboxIndeterminate.tsx).

The difference is that when deselecting a single checkbox, the others are deselected too. This does not happen when selecting. It could be an error in my code, but I cannot find it.

I'm using version `2.1.0-alpha1`.

[Screencast from 2023-03-15 11-00-49.webm](https://user-images.githubusercontent.com/498086/225279956-4e49d748-8335-44a4-80ad-e7d1c2d6899f.webm)

**Comment by rolfsmeds** [comment] 2023-12-13 08:52
Closing as (effectively) a duplicate of https://github.com/vaadin/react-components/issues/133

**Closed by rolfsmeds** 2023-12-13 08:52 UTC
