### ISSUE TITLE
Provide attribute Custom Value Entry feature for Multi-Select Combo Box react component 

### ISSUE THREAD

**Issue by manideeps** [vaadin/react-components#238] opened 2024-02-29 05:03 UTC
Custom Value Entry feature for Multi-Select Combo Box react component is not supported. Reference document says to configure custom value entry like in Combo Box but corresponding attributes are not available in Multi-Select Combo Box

**Comment by web-padawan** [comment] 2024-02-29 08:15
Thanks for the issue. Part of the problem is the lack of `onCustomValueSet` event in `MultiSelectComboBox`:

```ts
export type MultiSelectComboBoxEventMap<T1> = Readonly<{
    onValidated: EventName<_MultiSelectComboBoxEventMap<T1>["validated"]>;
    onChange: EventName<_MultiSelectComboBoxEventMap<T1>["change"]>;
    onInput: EventName<_MultiSelectComboBoxEventMap<T1>["input"]>;
    onSelectedItemsChanged: EventName<_MultiSelectComboBoxEventMap<T1>["selected-items-changed"]>;
    onOpenedChanged: EventName<_MultiSelectComboBoxEventMap<T1>["opened-changed"]>;
    onFilterChanged: EventName<_MultiSelectComboBoxEventMap<T1>["filter-changed"]>;
    onInvalidChanged: EventName<_MultiSelectComboBoxEventMap<T1>["invalid-changed"]>;
}>;
```

Whereas in `ComboBox` the corresponding handler is present in the generated event map:

```ts
export type ComboBoxEventMap<T1> = Readonly<{
    onValidated: EventName<_ComboBoxEventMap<T1>["validated"]>;
    onChange: EventName<_ComboBoxEventMap<T1>["change"]>;
    onInput: EventName<_ComboBoxEventMap<T1>["input"]>;
    onCustomValueSet: EventName<_ComboBoxEventMap<T1>["custom-value-set"]>;
    onSelectedItemChanged: EventName<_ComboBoxEventMap<T1>["selected-item-changed"]>;
    onValueChanged: EventName<_ComboBoxEventMap<T1>["value-changed"]>;
    onInvalidChanged: EventName<_ComboBoxEventMap<T1>["invalid-changed"]>;
    onOpenedChanged: EventName<_ComboBoxEventMap<T1>["opened-changed"]>;
    onFilterChanged: EventName<_ComboBoxEventMap<T1>["filter-changed"]>;
}>;
```

This `onCustomValueSet` handler is necessary too add custom value to the list of items. I'll work on adding it.

**Comment by web-padawan** [comment] 2024-03-08 12:38
Tested this with the latest 24.4.0-alpha16 and now `onCustomValueSet` is there. Here's how it can be used:

```tsx
export default function () {
  const [items, setItems] = useState(['foo', 'bar', 'baz']);

  return (
    <MultiSelectComboBox
      items={items}
      allowCustomValue
      onCustomValueSet={(e) => {
        setItems([...items, e.detail]);
      }}
    />
  );
}
```

The same will also work with the next patch release in `2.3` branch as the WC fix was backported. Closing as fixed.

**Closed by web-padawan** 2024-03-08 12:38 UTC
Labels: bug
