### ISSUE TITLE
Exclude list is not applied in Crud

### ISSUE THREAD

**Issue by cromoteca** [vaadin/react-components#78] opened 2023-03-30 09:09 UTC
This Lit code:
```html
      <vaadin-crud
        exclude="lastName, address, id, subscribe, membership, pictureUrl, manager"
        .items="${this.items}"
      ></vaadin-crud>
```
should be translated as:
```tsx
    <Crud
      items={people}
      exclude="lastName, address, id, subscribe, membership, pictureUrl, manager"
    />
```
But all the columns are shown anyway. The exclusion works fine in the row editor dialog though.

Using `"@hilla/react-components": "2.0.2"`.

Note the addition of the `Address` header in the screenshot:

![image](https://user-images.githubusercontent.com/498086/228787427-b943eeb6-c41d-4aa6-a964-eb032bf603a7.png)

**Comment by Lodin** [comment] 2023-06-19 11:14
I was unable to reproduce this issue on small amount of data: 3 columns, I hid 2 of them, and everything worked as expected. @cromoteca, could you provide your dataset or the link to the affected project?

**Comment by web-padawan** [comment] 2023-12-13 14:13
Tested with a [bigger dataset](https://github.com/vaadin/web-components/blob/653ca7fb195da264f7d80deca840d99d350270fe/packages/grid-pro/test/visual/users.js#L1) and could not reproduce this either. The following worked for me:

```jsx
<Crud items={users} exclude="name,married"></Crud>
```

Looks like this is no longer relevant since `"@hilla/react-components": "2.1.0"`. Closing.

**Closed by web-padawan** 2023-12-13 14:13 UTC
Labels: Impact: Low, Severity: Major, DX
