### ISSUE TITLE
MessageInput onSubmit does not fire on submit

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/react-components#51] opened 2023-01-06 01:08 UTC
The following code does not print anything to the console 
```
<MessageInput onSubmit={(e: any) => console.log(e)}/>
```

**Comment by marcushellberg** [comment] 2023-01-07 18:42
Related: https://github.com/vaadin/web-components/issues/5258

**Comment by platosha** [comment] 2023-01-25 10:24
Seems to be caused by https://github.com/vaadin/web-components/issues/5258, which already fixed. Closing for now, let me know if the issue occurs.

**Closed by platosha** 2023-01-25 10:24 UTC
