### ISSUE TITLE
MenuBar item component doesn't accept a React component

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/react-components#132] opened 2023-08-01 07:57 UTC
There's currently no React-friendly way to define a `component` for a `MenuBar` item:

<img width="686" alt="Screenshot 2023-08-01 at 10 55 44" src="https://github.com/vaadin/react-components/assets/1222264/ca360f7a-d735-43d6-9b16-4a9fa4307ee9">

The `MenuBar` wrapper could provide a React-friendly API for this and handle mapping to the underlying web component API internally.

**Comment by web-padawan** [comment] 2023-12-07 08:11
Duplicate of #54

**Closed by web-padawan** 2023-12-07 08:11 UTC
