### ISSUE TITLE
Custom editor doesn't work with Grid Pro

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/react-components#135] opened 2023-08-09 11:02 UTC
`GridProEditColumn` doesn't support a custom editor.

The reason is most likely that a custom React based `editModeRenderer` works asynchronously while the Grid pro web component expects the editor component to be there synchronously when a cell enters edit mode.

**Comment by web-padawan** [comment] 2023-12-07 08:12
Duplicate of #75

**Closed by web-padawan** 2023-12-07 08:12 UTC
